from sqlalchemy import Column, Integer, String, Boolean, DateTime, Date, Float
from app.database import Base


class Partner(Base):
    __tablename__ = 'res_partner'

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String)
    company_id = Column(Integer)
    create_date = Column(DateTime)
    display_name = Column(String)
    date = Column(Date)
    title = Column(Integer)
    parent_id = Column(Integer)
    ref = Column(String)
    lang = Column(String)
    tz = Column(String)
    user_id = Column(Integer)
    vat = Column(String)
    website = Column(String)
    comment = Column(String)
    credit_limit = Column(Float)
    active = Column(Boolean)
    employee = Column(Boolean)
    function = Column(String)
    type = Column(String)
    street = Column(String)
    street2 = Column(String)
    zip = Column(String)
    city = Column(String)
    state_id = Column(Integer)
    country_id = Column(Integer)
    partner_latitude = Column(Integer)
    partner_longitude = Column(Integer)
    email = Column(String)
    phone = Column(String)
    mobile = Column(String)
    is_company = Column(Boolean)
    industry_id = Column(Integer)
    color = Column(Integer)
    partner_share = Column(Boolean)
    commercial_partner_id = Column(Integer)
    commercial_company_name = Column(String)
    company_name = Column(String)
    create_uid = Column(Integer)
    write_uid = Column(Integer)
    write_date = Column(DateTime)
    message_main_attachment_id = Column(Integer)
    email_normalized = Column(String)
    message_bounce = Column(Integer)
    signup_token = Column(String)
    signup_type = Column(String)
    signup_expiration = Column(DateTime)
    partner_gid = Column(Integer)
    additional_info = Column(String)
    phone_sanitized = Column(String)
